dependencies:
  - base
  - patches-vector
  - semigroups
  - containers
  - vector

library:
  source-dirs:
    - src

tests:
  spec:
    main: Spec.hs
    source-dirs:
      - test
      - src
    dependencies:
      - hspec
      - QuickCheck
      - checkers
      - hspec-checkers
      - quickcheck-instances
