name: crdt-tree-vector
version: "0.1"

dependencies:
  - base
  - edit-distance-vector
  - semigroups
  - containers
  - vector
  - deepseq
  - hashable

ghc-options:
  -Wall -fno-warn-name-shadowing

library:
  source-dirs:
    - src

tests:
  spec:
    main: Spec.hs
    source-dirs:
      - test
    dependencies:
      - base-compat
      - hspec
      - QuickCheck
      - checkers
      - hspec-checkers
      - quickcheck-instances
      - deepseq
      - crdt-tree-vector

benchmarks:
  benchmarks:
    main: Benchmarks.hs
    source-dirs:
      - benchmarks
      - src
    ghc-options: -O1
    dependencies:
      - criterion
